---
- name: CiviCRM | Install unzip for plugin
  sudo: yes
  apt: pkg=unzip
  tags: civi

- name: CiviCRM | Download wordpress plugin
  command: wget http://downloads.sourceforge.net/project/civicrm/civicrm-stable/{{ civicrm_version }}/civicrm-{{ civicrm_version }}-wordpress.zip
  tags: civi

- name: CiviCRM | Extract plugin
  command: unzip civicrm-{{ civicrm_version }}-wordpress.zip -d /var/www/wp-content/plugins 
  tags: civi

- name: CiviCRM | Create the civicrm database
  mysql_db: login_user={{mysql_user}} login_password={{mysql_password}} name={{civicrm_database}} state=present
  tags: civi

- name: CiviCRM | Create civicrm database user
  mysql_user: login_user={{mysql_user}} login_password={{mysql_password}} name={{ civicrm_database_user }} password={{ civicrm_database_password }} priv={{ civicrm_database }}.*:ALL host='localhost' state=present
  tags: civi

- name: CiviCRM | Create files directory
  command: chdir=/var/www/wp-content/plugins/ mkdir files
  tags: civi

- name: CiviCRM | Make files directory writeable
  command: chdir=/var/www/wp-content/plugins/ chmod 777 files
  tags: civi

- name: CiviCRM | Give ownership of new files to web user
  sudo: yes
  shell: chdir=/var/www/wp-content/plugins/ chown -R www-data:www-data *
  tags: civi
