---

- name: Install http and php etc
  yum: name={{ item }} state=present
  with_items:
   - httpd
   - php
   - php-mysql
   - php-pear
   - php-mbstring
   - php-gd
   - php-xml

- name: http service state
  service: name=httpd state=started enabled=yes

- name: Configure SELinux to allow httpd to connect to remote database
  seboolean: name=httpd_can_network_connect_db state=true persistent=yes
  when: sestatus.rc != 0

- name: discover drush
  sudo: yes
  command: pear channel-discover pear.drush.org
  ignore_errors: true

- name: install drush
  sudo: yes
  command: pear install drush/drush
  ignore_errors: true

- name: Check if drupal folder exists
  stat: path=/vagrant/{{ drupal_db }}
  register: check_drupal_path

- name: install and configure drupal 7
  sudo: yes
  shell: drush -y dl drupal --destination=/vagrant --drupal-project-rename={{ drupal_db }} && drush -y site-install standard --root=/vagrant/{{ drupal_db }} --account-name=admin --account-pass=admin --site-name="{{ drupal_db }}" --db-url=mysql://{{ db_user }}:{{ db_user_password }}@localhost/{{ drupal_db }}
  when: check_drupal_path.stat.exists == false

# - name: CiviCRM | Install unzip for plugin
#   sudo: yes
#   apt: pkg=unzip
#   tags: civi

# - name: CiviCRM | Create files directory
#   command: chdir=/var/www/wp-content/plugins/ mkdir files
#   tags: civi

# - name: CiviCRM | Make files directory writeable
#   command: chdir=/var/www/wp-content/plugins/ chmod 777 files
#   tags: civi

# - name: CiviCRM | Give ownership of new files to web user
#   sudo: yes
#   shell: chdir=/var/www/wp-content/plugins/ chown -R www-data:www-data *
#   tags: civi