---

- name: install mysql packages
  action: yum pkg={{ item }} state=installed
  with_items:
   - mysql-server
   - MySQL-python

- name: configure SELinux to start mysql on any port
  seboolean: name=mysql_connect_any state=true persistent=yes
  when: sestatus.rc != 0

- name: create Mysql configuration file
  action: template src=my.cnf.j2 dest=/etc/my.cnf
  notify:
  - restart mysql

- name: start Mysql Service
  service: name=mysqld state=started enabled=true

# - name: insert iptables rule
#   lineinfile: dest=/etc/sysconfig/iptables state=present regexp="{{ mysql_port }}"
#               insertafter="^:OUTPUT " line="-A INPUT -p tcp  --dport {{ mysql_port }} -j  ACCEPT"
#   notify: restart iptables

- name: create application databases
  mysql_db: name={{ item }} state=present
  with_items:
   - "{{ drupal_db }}"
   - "{{ civicrm_db }}"

- name: create application DB user
  mysql_user: name={{ db_user }} password={{ db_user_password }} priv=*.*:ALL host='%' state=present