---

- name: install mysql packages
  action: yum pkg={{ item }} state=installed
  with_items:
   - mysql-server
   - MySQL-python

- name: create Mysql configuration file
  action: template src=my.cnf.j2 dest=/etc/my.cnf
  notify:
  - restart mysql

- name: start Mysql Service
  service: name=mysqld state=started enabled=true

- name: create application databases
  mysql_db: name={{ item }} state=present
  with_items:
   - "{{ drupal_db }}"
   - "{{ civicrm_db }}"

- name: create application DB user
  mysql_user: name={{ db_user }} password={{ db_user_password }} priv=*.*:ALL host='%' state=present