---

- name: install apache and php modules
  yum: name={{ item }} state=present
  with_items:
   - httpd
   - php
   - php-mysql
   - php-pear
   - php-mbstring
   - php-gd
   - php-xml

- name: http service state
  service: name=httpd state=started enabled=yes

- name: configure SELinux to allow httpd to connect to remote database
  seboolean: name=httpd_can_network_connect_db state=true persistent=yes
  when: sestatus.rc != 0

- name: discover drush pear channel
  sudo: yes
  command: pear channel-discover {{ item }} creates=/usr/share/pear/.channels/{{ item }}.reg
  with_items:
   - pear.drush.org

- name: update drush pear channel
  sudo: yes
  command: pear channel-update {{ item }}
  register: out
  changed_when: "out.stdout.endswith('succeeded')"
  with_items:
   - pear.drush.org

- name: install/upgrade drush
  sudo: yes
  command: pear upgrade drush/drush
  register: out
  changed_when: "'upgrade ok' in out.stdout"

- name: install drupal
  sudo: yes
  command: drush -y dl drupal --destination=/vagrant --drupal-project-rename={{ drupal_db }} creates=/vagrant/{{ drupal_db }}

- name: configure drupal
  sudo: yes
  command: drush -y site-install standard --root=/vagrant/{{ drupal_db }} --account-name=admin --account-pass=admin --site-name="{{ drupal_db }}" --db-url=mysql://{{ db_user }}:{{ db_user_password }}@localhost/{{ drupal_db }} creates=/vagrant/{{ drupal_db }}/sites/all/modules/user

# - name: CiviCRM | Install unzip for plugin
#   sudo: yes
#   apt: pkg=unzip
#   tags: civi

# - name: CiviCRM | Create files directory
#   command: chdir=/var/www/wp-content/plugins/ mkdir files
#   tags: civi

# - name: CiviCRM | Make files directory writeable
#   command: chdir=/var/www/wp-content/plugins/ chmod 777 files
#   tags: civi

# - name: CiviCRM | Give ownership of new files to web user
#   sudo: yes
#   shell: chdir=/var/www/wp-content/plugins/ chown -R www-data:www-data *
#   tags: civi